version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:20.18
      - image: cimg/postgres:16.2
        environment:
          NODE_ENV: test
          DB_HOST: localhost
          DB_PORT: 5434
          DB_USERNAME: postgres
          DB_PASSWORD: postgres
          DB_DATABASE: template_test_db

      - image: cimg/postgres:16.4
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: template_test_db

    environment:
      NODE_ENV: test
      DB_HOST: localhost
      DB_PORT_TEST: 5434
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME_TEST: template_test_db

    steps:
      - checkout

      - restore_cache:
          keys:
            - pnpm-store-v1-{{ checksum "pnpm-lock.yaml" }}

      - run:
          name: Check versions
          command: |
            node -v
            pnpm -v

      - run:
          name: Clean install
          command: |
            rm -rf node_modules apps/*/node_modules
            pnpm config set store-dir .pnpm-store
            pnpm install --frozen-lockfile

      - run:
          name: Install dependencies
          command: |
            pnpm config set store-dir .pnpm-store
            pnpm install --frozen-lockfile --config.optional=true
      - save_cache:
          paths:
            - .pnpm-store
          key: pnpm-store-v2-{{ checksum "pnpm-lock.yaml" }}

      - run:
          name: Check rolldown native binding
          command: |
            ls node_modules/@rolldown || true
            pnpm list @rolldown/binding-linux-x64-gnu -r || true

      - run:
          name: Run e2e tests with coverage
          command: pnpm test

      - store_artifacts:
          path: coverage
          destination: coverage

      - store_test_results:
          path: test-results

workflows:
  test:
    jobs:
      - test
