version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:20.18
        environment:
          NODE_ENV: test
          DB_HOST: localhost
          DB_PORT: 5432
          DB_PORT_TEST: 5432
          DB_USER: postgres
          DB_USERNAME: postgres
          DB_PASSWORD: postgres
          DB_NAME_TEST: template_test_db
          DB_DATABASE: template_test_db

      - image: cimg/postgres:16.4
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: template_test_db

    steps:
      - checkout

      - restore_cache:
          keys:
            - pnpm-store-v2-{{ checksum "pnpm-lock.yaml" }}

      - run:
          name: Check versions
          command: |
            node -v
            pnpm -v

      - run:
          name: Install dependencies
          command: |
            rm -rf node_modules apps/*/node_modules
            pnpm config set store-dir .pnpm-store
            pnpm install --frozen-lockfile --config.optional=true

      - save_cache:
          paths:
            - .pnpm-store
          key: pnpm-store-v2-{{ checksum "pnpm-lock.yaml" }}

      - run:
          name: Wait for Postgres
          command: |
            sudo apt-get update
            sudo apt-get install -y postgresql-client
            until pg_isready -h localhost -p 5432 -U postgres; do
              echo "Waiting for postgres..."
              sleep 2
            done

      - run:
          name: Create test env
          command: |
            printf "%s\n" \
            "NODE_ENV=test" \
            "PORT=3000" \
            "DB_HOST=localhost" \
            "DB_PORT=5432" \
            "DB_PORT_TEST=5432" \
            "DB_USER=postgres" \
            "DB_USERNAME=postgres" \
            "DB_PASSWORD=postgres" \
            "DB_NAME=template_db" \
            "DB_NAME_TEST=template_test_db" \
            "DB_DATABASE=template_test_db" \
            "JWT_SECRET=1234567890abcdefghijklmnopqrstuvwxyz" \
            "JWT_EXPIRES_IN=7d" \
              > apps/back/.env

      - run:
          name: Run e2e tests with coverage
          command: pnpm test

workflows:
  test:
    jobs:
      - test
