GET http://localhost:3000/api/v1/user/ba0b137d-bc57-4eb1-9600-2704bf72fd2e
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImJhMGIxMzdkLWJjNTctNGViMS05NjAwLTI3MDRiZjcyZmQyZSIsImVtYWlsIjoiam9obkBleGFtcGxlLmNvbSIsInJvbCI6MCwiYWN0aXZpdGllcyI6WzNdLCJuYW1lIjoiSm9obiBEb2UiLCJpYXQiOjE3NzQzODQ2OTMsImV4cCI6MTc3NDk4OTQ5M30.BfjcWrL7Qal79ddDxX8uIjNZ1oupgZql82kk5xReBlE

GET http://localhost:3000/api/v1/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImJhMGIxMzdkLWJjNTctNGViMS05NjAwLTI3MDRiZjcyZmQyZSIsImVtYWlsIjoiam9obkBleGFtcGxlLmNvbSIsInJvbCI6MCwiYWN0aXZpdGllcyI6WzNdLCJuYW1lIjoiSm9obiBEb2UiLCJpYXQiOjE3NzQzODQ2OTMsImV4cCI6MTc3NDk4OTQ5M30.BfjcWrL7Qal79ddDxX8uIjNZ1oupgZql82kk5xReBlE

POST http://localhost:3000/api/v1/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImJhMGIxMzdkLWJjNTctNGViMS05NjAwLTI3MDRiZjcyZmQyZSIsImVtYWlsIjoiam9obkBleGFtcGxlLmNvbSIsInJvbCI6MCwiYWN0aXZpdGllcyI6WzNdLCJuYW1lIjoiSm9obiBEb2UiLCJpYXQiOjE3NzQzODQ2OTMsImV4cCI6MTc3NDk4OTQ5M30.BfjcWrL7Qal79ddDxX8uIjNZ1oupgZql82kk5xReBlE

{
  "name": "John Doe",
  "email": "john@example.com",
  "password": "Abcd!123456789"
}

PATCH http://localhost:3000/api/v1/user/ba0b137d-bc57-4eb1-9600-2704bf72fd2e
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImJhMGIxMzdkLWJjNTctNGViMS05NjAwLTI3MDRiZjcyZmQyZSIsImVtYWlsIjoiam9obkBleGFtcGxlLmNvbSIsInJvbCI6MCwiYWN0aXZpdGllcyI6WzNdLCJuYW1lIjoiSm9obiBEb2UiLCJpYXQiOjE3NzQzODQ2OTMsImV4cCI6MTc3NDk4OTQ5M30.BfjcWrL7Qal79ddDxX8uIjNZ1oupgZql82kk5xReBlE

{
  "name": "John Doe 2",
  "email": "john@example.com",
  "password": "Abcd!123456789"
}

DELETE http://localhost:3000/api/v1/user/ba0b137d-bc57-4eb1-9600-2704bf72fd23
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImJhMGIxMzdkLWJjNTctNGViMS05NjAwLTI3MDRiZjcyZmQyZSIsImVtYWlsIjoiam9obkBleGFtcGxlLmNvbSIsInJvbCI6MCwiYWN0aXZpdGllcyI6WzNdLCJuYW1lIjoiSm9obiBEb2UiLCJpYXQiOjE3NzQzODQ2OTMsImV4cCI6MTc3NDk4OTQ5M30.BfjcWrL7Qal79ddDxX8uIjNZ1oupgZql82kk5xReBlE