GET http://localhost:3000/user/bcf0f570-1ac0-4e9e-9993-f8a501b0ab08

GET http://localhost:3000/user

POST http://localhost:3000/user
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john@example.com",
  "password": "secret"
}

PATCH http://localhost:3000/user/bcf0f570-1ac0-4e9e-9993-f8a501b0ab08
Content-Type: application/json

{
  "name": "John Doe 2",
  "email": "john@example.com",
  "password": "secret"
}

DELETE http://localhost:3000/user/bcf0f570-1ac0-4e9e-9993-f8a501b0ab08